### ISSUE TITLE
Quesition: change gesture to activiate

### ISSUE THREAD

**Issue by mpiparo** [retroportalstudio/focused_menu#5]
Hi. thanks for creating this, works great.
I do have a question on how I would be able to change the activation from a long-press to a tap?
I didn't see a configuration for it, but I do notice an onPressed in the FocusedMenuHolder and was wondering if there was a way to use that to display the menu on tap instead of long-press.

Any suggestions would be really appreciated.
thanks!

**Comment by aleonnet** [comment]
I've just pushed a PR to replace this behaviour https://github.com/aleonnet/focused_menu/blob/master/lib/focused_menu.dart

**Comment by melaLetics** [comment]
I have now played around a little with the onPressed interface, but I couldn't get the OnTap to open the FocusedMenuItems. So far I have only seen examples in which onPressed is assigned () {}.

**Comment by sxdpz23** [comment]
Hey there!

Can you add another field that will trigger the same focused menu on the "onPressed" action?? Because I have a situation in which I want the menu on single tap action.

Hope you read this comment and work on an update to add the following functionality. 

P.S. I am thinking of forking it and doing it myself, please go over the same and check whether it works fine for all. And awesome work on the focussed menu. Thanks for such a wonderful and easy to use package.

**Comment by henriquezanfa** [comment]
This functionality was added with the #8 PR.
